# Generated by Django 5.2.9 on 2026-02-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_owner_full_name_alter_owner_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
